export const CADE_BIO =
  "I'm Cade a 3rd year CS student with a bit of SQL knowledge (As my current Co-Op has me working with it to pull data from their Oracle DB). Working with Data is a strength of mine but I've never set up my own database so most of this course will still be new to me. In general, I enjoy working with everything other than UI because it hurts my soul. I'm a windows and android person though learning to use Linux would definitely be a boon. Aside from work and school, I'm heavily involved in the SCD so if you're interested in anything CS look us up! We plan to participate in several hackathons around Michigan this term and welcome all levels of talent! When I'm all out of productivity I spend time with my Two GSP's Koda and Diesel (2 and 4 respectively), work out (that's a lie), and read (mostly a lie). Of course, I like video games but since half of my schoolwork is online and I have a desk job now, it's a lot harder to enjoy staring at a computer any longer than I have to. I also love TTRPG's and play/run them when time permits, so twice a year. I look forward to meeting you all and have a great semester!";

export const JACK_BIO_PARA_1 =
  "Hello, my name is Jack Flenna. I should be completing this degree in December of next year. I have actually already completed a BS in Economics at MSU with a minor in Math in 2017. I worked for ~2 years at an actuarial consultancy and decided to change career paths. Last Summer I interned at Rocket Mortgage and was hired on as an Associate Software Engineer when the internship ended. My salary and hours have been prorated to 25hrs/week so that I can finish this degree while working. The job is actually super interesting for the most part, and it has given me the opportunity to do some database design in a couple of live applications. However, we rarely use SQL databases. The application I'm on right now actually does use a SQL database, but we use EF Core so I still don't have to write much actual SQL code! Outside of CS stuff, I like watching movies - They can be anything from old Kurosawa movies to whatever's coming out now. I enjoy reading books with pretty much the same variety as with movies.";

export const JACK_BIO_PARA_2 =
  "I also enjoy doing a bunch of different puzzles. I do the NYT crossword almost everyday. I'm always in 2-3 different chess tournaments (though my skills have been falling off hard lately). Plus I've been trying to get into sudoku lately.";

export const GREY_BIO =
  "Hello, I am Grey Slatina and this is my 3rd year at wayne. I am a Computer Science major and am currently fast tracking my masters in Artificial Intelligence. I used SQL very briefly during a certification program but have not touched it since then so I will be a little rusty. However I did work heavily with Firebase in my previous semester for the Software Engineering course. I am jack of all trades user, meaning my laptop is a Mac, my desktop is Windows, and I have used UNIX/Linux on both machines. I am not partial towards any operation system and I find all 3 useful in some way! This has happened due to my family using me as their personal IT department for most of my life, I'm sure some of you can resonate with that. Some hobbies I have are body modification (Tattoos, piercings, etc.) and sleeping. Other than that I spend most of my free time with my corgi Ein and my Maine coon/Gremlin Sozin. I look forward to working you all and here is to a good semester!";

export const MANPREET_BIO =
  "Hi! I'm Manpreet and I am a third-year student here at WSU, majoring in CS and minoring in Business! I am excited for this class as I've never dealt with databases before. This is definitely new territory for me, but I'm looking forward to learning about new topics! Outside of class, I'm active in Society of Women Engineers. I am currently the lead coordinator for an event we hold during National Engineers Week called FutureSWE, in which we invite high school students to learn about different engineering disciplines. This will be the first in-person FutureSWE we've had in a few years, so I'm really excited to see how it all works out! Other than that, I love solving all kinds puzzles--crosswords, jigsaw, sudoku, you name it! The last jigsaw puzzle I did was pretty cool: the Orion Nebula with metallic embellishments.";
